name: Nightly build Android

on:
  push:
    tags:
      - 'Nightly'

jobs:
  set-revision:
    name: set revision
    runs-on: ubuntu-22.04
    outputs:
      output1: ${{ steps.out1.outputs.revision }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: detect revision
      run: |
        read text < ./src/simutrans/revision.h
        revision=${text:17:5}
        echo "revision=$revision" >> $GITHUB_ENV
    - id: out1
      run: echo "revision=$revision" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [set-revision]
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: 'gh-clone/simutrans'

    - name: Install dependencies
      run: |
        sudo add-apt-repository universe
        sudo apt-get -yqq update
        sudo dpkg --add-architecture i386
        sudo apt-get -yqq update
        sudo apt-get -ym install curl expect git libc6:i386 libgcc1:i386 libncurses6:i386 libstdc++6:i386 zlib1g:i386 openjdk-21-jdk wget unzip vim make subversion zip
        sudo apt remove cmake

    - name: Install dependencies1
      working-directory: /usr/local/lib/android/sdk
      run: |
        echo "$(find .. -maxdepth 3 -type d)"
        mv cmdline-tools/latest cmdline-tools/existing
        yes | cmdline-tools/existing/bin/sdkmanager --licenses
        sudo yes | cmdline-tools/existing/bin/sdkmanager --install "cmdline-tools;latest"
        echo "/usr/local/lib/android/sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        sudo yes | cmdline-tools/latest/bin/sdkmanager --install "platform-tools"
        echo "/usr/local/lib/android/sdk/platform-tools" >> $GITHUB_PATH
        sudo yes | cmdline-tools/latest/bin/sdkmanager --install "build-tools;35.0.0"
        echo "/usr/local/lib/android/sdk/build-tools/35.0.0" >> $GITHUB_PATH
        sudo yes | cmdline-tools/latest/bin/sdkmanager --install "cmake;3.31.6"
        echo "/usr/local/lib/android/sdk/cmake/3.31.6/bin" >> $GITHUB_PATH
        sudo yes | cmdline-tools/latest/bin/sdkmanager --install "ndk;29.0.14206865"
        echo "/usr/local/lib/android/sdk/ndk/29.0.14206865" >> $GITHUB_PATH
        echo "ANDROID_NDK=/usr/local/lib/android/sdk/ndk/29.0.14206865" >> $GITHUB_ENV
        echo "($pwd)/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
        ln -s llvm-objdump ${ANDROID_HOME}/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/objdump
        echo "Github path ($PATH)"
        echo "Github path ($ENV)"

    - name: Setup Android SDK environment variables
      run: |
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64" >> $GITHUB_ENV

    - name: Set up android project
      working-directory: /android-sdl
      run: |
        git clone --depth 1 https://github.com/simutrans/simutrans-android-project
        cd simutrans-android-project
        git submodule init
        git submodule update
        cd simutrans/jni/SDL
        git revert 53dbe18  --no-commit
        cd ../../..

        cp -r $GITHUB_WORKSPACE/gh-clone/simutrans simutrans/jni/simutrans
        cp -r simutrans/jni/SDL/android-project/app/src/main/java simutrans/src/main
        cd simutrans/jni
        cp -v simutrans/src/android/logo_72.png ../src/main/res/mipmap-hdpi/ic_launcher.png
        cp -v simutrans/src/android/logo_48.png ../src/main/res/mipmap-mdpi/ic_launcher.png
        cp -v simutrans/src/android/logo_96.png ../src/main/res/mipmap-xhdpi/ic_launcher.png
        cp -v simutrans/src/android/logo_144.png ../src/main/res/mipmap-xxhdpi/ic_launcher.png
        cp -v simutrans/src/android/logo_192.png ../src/main/res/mipmap-xxxhdpi/ic_launcher.png
        chmod +755 simutrans/src/android/AndroidPreBuild.sh
        chmod +755 simutrans/tools/lang_files_standard.sh
        chmod +755 simutrans/tools/get_pak.sh
        ./simutrans/src/android/AndroidPreBuild.sh
        cp -rf simutrans/simutrans/. ../src/main/assets


    - name: Build libraries
      working-directory: /android-sdl/simutrans-android-project/simutrans/jni
      run: |
        ./build_libraries.sh
        # Fluidsynth is a PITA to build; using the prebuilt release instead
        wget https://github.com/FluidSynth/fluidsynth/releases/download/v2.5.1/fluidsynth-2.5.1-android24.zip
        unzip fluidsynth-*.zip -d fluidsynth

    - name: Build Simutrans for Android
      env:
          SIGNING_KEYSTORE: /android-sdl/simutrans-android-project/simutrans/jni/simutrans/src/android/Simutrans-upload.keystore
          SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_UPLOAD_KEYSTORE_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_UPLOAD_KEYSTORE_PASS }}
          SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_UPLOAD_KEYSTORE_PASS }}
      working-directory: gh-clone/simutrans
      run: |
        echo "action_state=yellow" >> $GITHUB_ENV
        sed -i "s/versionCode [0-9]\+/versionCode $(./tools/get_revision.sh)/" /android-sdl/simutrans-android-project/simutrans/build.gradle
        VERSION=`sed -n 's/#define SIM_VERSION_MAJOR *\([0-9]*\)$/\1/ p' <src/simutrans/simversion.h`.`sed -n 's/#define SIM_VERSION_MINOR *\([0-9]*\)$/\1/ p' <src/simutrans/simversion.h`.`sed -n 's/#define SIM_VERSION_PATCH *\([0-9]*\)$/\1/ p' <src/simutrans/simversion.h`
        NIGHTLY=`sed -n 's/#define SIM_VERSION_BUILD SIM_BUILD_NIGHTLY/ Nightly/ p' <src/simutrans/simversion.h``sed -n 's/#define SIM_VERSION_BUILD SIM_BUILD_RELEASE_CANDIDATE/ Release candidate/ p' <src/simutrans/simversion.h`
        sed -i 's/versionName.*$/versionName "'"$VERSION$NIGHTLY"'"/' /android-sdl/simutrans-android-project/simutrans/build.gradle
        sed -i '/distributionUrl/s/gradle-8.3-all.zip/gradle-8.3-all.zip/' /android-sdl/simutrans-android-project/gradle/wrapper/gradle-wrapper.properties
        cd /android-sdl/simutrans-android-project
        cat simutrans/build.gradle
        #cp project/jni/simutrans/src/android/signBundle.sh .
        #chmod 555 ./signBundle.sh
        #./build.sh -b simutrans
        ./gradlew assembleRelease
        ./gradlew bundleRelease

        cd /android-sdl/simutrans-android-project/simutrans/build/outputs/bundle/release
        mkdir whatsNewDirectory
        echo `cd $GITHUB_WORKSPACE/gh-clone/simutrans && git log --pretty=format:'%s' -1` > whatsNewDirectory/whatsnew-en-US

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /android-sdl/simutrans-android-project/simutrans/build/outputs/apk/release/simutrans-release-unsigned.apk
        asset_name: simuandroid-nightly_r.apk
        tag: Nightly
        overwrite: true
