name: Nightly build Linux x64

on:
  push:
    tags:
      - 'Nightly_a'

jobs:
  set-revision:
    name: set revision
    runs-on: ubuntu-26.04
    outputs:
      output1: ${{ steps.out1.outputs.revision }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: detect revision
      run: |
        read text < ./src/simutrans/revision.h
        revision=${text:17:5}
        echo "revision=$revision" >> $GITHUB_ENV
    - id: out1
      run: echo "revision=$revision" >> $GITHUB_OUTPUT

