name: Nightly build Linux x64

on:
  push:
    tags:
      - 'Nightly_a'

jobs:
  set-revision:
    name: set revision
    runs-on: ubuntu-26.04
    outputs:
      output1: ${{ steps.out1.outputs.revision }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: detect revision
      run: |
        read text < ./src/simutrans/revision.h
        revision=${text:17:5}
        echo "revision=$revision" >> $GITHUB_ENV
    - id: out1
      run: echo "revision=$revision" >> $GITHUB_OUTPUT

  windows_SDL3-nightly:
    name: Simutrans Windows SDL3
    runs-on: windows-2022
    needs: [set-revision]

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: compile simutrans
      run: |
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\Simutrans-SDL3.vcxproj /p:Configuration=Release /p:Platform=x64 /p:TargetName=Simutrans_SDL3_x64
        cd $Env:GITHUB_WORKSPACE\
        copy build\SDL3\Simutrans_SDL3_x64.exe simutrans\Simutrans.exe

    - name: load translate files
      run: |
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/download.php
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/data/language_pack-Base+texts.zip -OutFile language_pack.zip

    - name: extract translate files
      run: Expand-Archive language_pack.zip src/simutrans/simutrans/text -Force
      shell: pwsh

    - name: delete ce translate files
      run: del src/simutrans/simutrans/text/ce.tab
      shell: pwsh

    - name: zip result
      run:  Compress-Archive simutrans simuwin_SDL3_x64-nightly.zip
      shell: pwsh

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: simuwin_SDL3_x64-nightly.zip
        asset_name: simuwin_SDL3_x64-nightly_r${{ needs.set-revision.outputs.output1 }}.zip
        tag: Nightly
        overwrite: true

  sim-mac-SDL3-arm:
    name: macOS (ARM)
    runs-on: macos-15
    needs: [set-revision]

    steps:
    - uses: actions/checkout@v6

    - name: install_dependencies
      run: |
        brew reinstall cmake pkg-config libpng freetype zstd sdl3 fluidsynth
    - name: build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cp ../revision.h ./revision.h
        cmake --build . --target install
    - name: distribute
      run: |
        cd build
        zip -r simumac-arm-nightly.zip simutrans
    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/simumac-arm-SDL3-nightly.zip
        asset_name: simumac-arm-SDL3-nightly_r${{ needs.set-revision.outputs.output1 }}.zip
        tag: Nightly
        overwrite: true
