name: Nightly build MacOS

on:
  push:
    tags:
      - 'Nightly'

jobs:
  sim-mac-sdl2:
    name: macOS (SDL2)
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Dependencies
        run: |
          brew reinstall cmake pkg-config libpng freetype zstd sdl2 fluidsynth
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --target install
      - name: Build Zip
        run: |
          cd build
          zip -r simumac_x86-nightly.zip simutrans
      - name: detect revision
        run: |
          read text < ./src/simutrans/revision.h
          revision=${text:17:5}
          echo "revision=$revision" >> $GITHUB_ENV
      - name: Upload Artifact (CI)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: simumac_x86-nightly.zip
          asset_name: simumac_x86-nightly_r${{ env.revision }}.zip
          #name: ${{ github.job }}-nightly
          #path:
          tag: Nightly
          overwrite: true

  sim-mac-arm:
    name: macOS (ARM)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: install_dependencies
      run: |
        brew reinstall cmake pkg-config libpng freetype zstd sdl2 fluidsynth
    - name: build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --target install
    - name: distribute
      run: |
        cd build
        zip -r simumac-arm-nightly.zip simutrans
    - name: detect revision
      run: |
        read text < ./src/simutrans/revision.h
        revision=${text:17:5}
        echo "revision=$revision" >> $GITHUB_ENV
    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/simumac-arm-nightly.zip
        asset_name: simumac-arm-nightly_r${{ env.revision }}.zip
        tag: Nightly
        overwrite: true


  makeobj-mac:
    name: macOS Makeobj
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: cp configs/config.${{ github.job }} config.default
      - name: Build
        run: make -j2 makeobj
      - name: zip result
        run: zip -r -9 makeobj_macos-nightly.zip build/default/makeobj/makeobj
      - name: detect revision
        run: |
          read text < ./src/simutrans/revision.h
          revision=${text:17:5}
          echo "revision=$revision" >> $GITHUB_ENV
      - name: Upload Artifact (CI)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: makeobj_macos-nightly.zip
          asset_name: makeobj_macos-x86-nightly_r${{ env.revision }}.zip
          #name: ${{ github.job }}-nightly
          #path: build/default/makeobj/makeobj
          tag: Nightly
          overwrite: true


  nettool-mac:
    name: macOS Nettool
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: cp configs/config.${{ github.job }} config.default
      - name: Build
        run: make -j2 nettool
      - name: zip result
        run: zip -r -9 nettool_mac-nightly.zip build/default/nettool/nettool
      - name: detect revision
        run: |
          read text < ./src/simutrans/revision.h
          revision=${text:17:5}
          echo "revision=$revision" >> $GITHUB_ENV
      - name: Upload Artifact (CI)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: nettool_mac-nightly.zip
          asset_name: nettool_mac-x86-nightly_r${{ env.revision }}.zip
          #name: ${{ github.job }}-nightly
          #path: build/default/nettool/nettool
          tag: Nightly
          overwrite: true
