name: Nightly build MacOS

on:
  push:
    tags:
      - 'Nightly'

jobs:
  sim-mac-sdl2:
    name: macOS (SDL2)
    runs-on: macos-11.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Dependencies
        run: |
          brew install autoconf automake freetype libpng pkg-config sdl2
      - name: Build
        run: |
          autoreconf -ivf
          ./configure CC=clang
          echo "CC += -std=gnu++14" >>config.default
          make BACKEND=sdl2 MULTI_THREAD=1 OPTIMISE=1 OSTYPE=mac USE_FREETYPE=1 USE_UPNP=0 USE_ZSTD=0 AV_FOUNDATION=1
          make src/OSX/getversion
      - name: Build Zip
        run: sh tools/distribute.sh
      - name: detect revision
        run: |
          read text < ./src/simutrans/revision.h
          revision=${text:17:5}
          echo "revision=$revision" >> $GITHUB_ENV
      - name: Upload Artifact (CI)
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: simumac.zip
          asset_name: simumac_SDL2-x86-nightly_r${{ env.revision }}.zip
          #name: ${{ github.job }}-nightly
          #path:
          tag: Nightly
          overwrite: true


  makeobj-mac:
    name: macOS Makeobj
    runs-on: macos-11.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: cp configs/config.${{ github.job }} config.default
      - name: Build
        run: make -j2 makeobj
      - name: zip result
        run: zip -r -9 makeobj_macos-nightly.zip build/default/makeobj/makeobj
      - name: detect revision
        run: |
          read text < ./src/simutrans/revision.h
          revision=${text:17:5}
          echo "revision=$revision" >> $GITHUB_ENV
      - name: Upload Artifact (CI)
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: makeobj_macos-nightly.zip
          asset_name: makeobj_macos-x86-nightly_r${{ env.revision }}.zip
          #name: ${{ github.job }}-nightly
          #path: build/default/makeobj/makeobj
          tag: Nightly
          overwrite: true


  nettool-mac:
    name: macOS Nettool
    runs-on: macos-11.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: cp configs/config.${{ github.job }} config.default
      - name: Build
        run: make -j2 nettool
      - name: zip result
        run: zip -r -9 nettool_mac-nightly.zip build/default/nettool/nettool
      - name: detect revision
        run: |
          read text < ./src/simutrans/revision.h
          revision=${text:17:5}
          echo "revision=$revision" >> $GITHUB_ENV
      - name: Upload Artifact (CI)
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: nettool_mac-nightly.zip
          asset_name: nettool_mac-x86-nightly_r${{ env.revision }}.zip
          #name: ${{ github.job }}-nightly
          #path: build/default/nettool/nettool
          tag: Nightly
          overwrite: true
