name: Makeobj Linux x64

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -ym install autoconf
        sudo apt-get -ym install libpng-dev
        sudo apt-get -ym install libbz2-dev

    - name: setup
      run: |
        autoconf
        ./configure
        echo "STATIC = 1" >>config.default
        cat config.default >>/dev/stderr

    - name: make makeobj
      run: |
        cd makeobj
        make

    - name: Rename result
      run: |
        cd makeobj
        zip -r -9 makeobj_linux-x64-nightly.zip makeobj

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: makeobj/makeobj_linux-x64-nightly.zip
        asset_name: makeobj_linux-x64-nightly.zip
        tag: Nightly
        overwrite: true
