name: Nightly build Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: install_dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -ym install libsdl2-dev
        sudo apt-get -ym install libfreetype6-dev
        sudo apt-get -ym install libminiupnpc-dev
        sudo apt-get -ym install libzstd-dev
        sudo apt-get -ym install libfluidsynth-dev
        sudo apt-get -ym install autoconf

    - name: build
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DOPTION_BUNDLE_LIBRARIES=ON -DSIMUTRANS_STEAM_BUILT=1
        cmake --build build -j$(nproc) --target install

    - name: distribute
      run: |
        cd build
        zip -r simulinux-x64-nightly.zip simutrans

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/simulinux-x64-nightly.zip
        asset_name: simulinux-x64-nightly.zip
        tag: Nightly
        overwrite: true

