name: Nightly Built Windows

on:
  push:
    tags:
      - 'Nightly'

jobs:
  winSDL2-64:
    runs-on: windows-latest
    steps:

      - name: Setup Mingw
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git zip unzip svn base-devel mingw-w64-x86_64-toolchain autoconf mingw-w64-x86_64-gcc mingw-w64-x86_64-freetype mingw-w64-x86_64-zstd mingw-w64-x86_64-libpng mingw-w64-x86_64-brotli mingw-w64-x86_64-SDL2 mingw-w64-x86_64-pkg-config

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepares NSIS plugins
        run: ./.github/prepare-nsis.ps1
        shell: powershell

      - name: Create nsis installer
        uses: joncloud/makensis-action@v2.0
        with:
          arguments: "/V3"
          additional-plugin-paths: NSIS_Plugins/Plugins
          script-file: src/Windows/nsis/onlineupgrade.nsi

      - name: CI-Build
        run: sh ./.github/build64-sdl2.sh
        shell: msys2 {0}

      - name: detect revision
        run: |
          $text = gc "$Env:GITHUB_WORKSPACE\src/simutrans/revision.h"
          $revision=$text.Substring(17,5)
          echo "revision=$revision" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - name: Update binaries of Nightly Release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./simuwin-SDL2-nightly_x64.zip
          asset_name: simuwin-SDL2-nightly_x64_r${{ env.revision }}.zip
          tag: Nightly
          overwrite: true
