name: Nightly built Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: |
        sudo apt-get -y update 
        sudo apt-get -ym install libsdl2-dev
        sudo apt-get -ym install libfreetype6-dev
        sudo apt-get -ym install libminiupnpc-dev
        sudo apt-get -ym install libbz2-dev
        sudo apt-get -ym install autoconf

    - name: setup
      run: |
        autoconf 
        ./configure
        revision="$(git log -1 --grep 'git-svn-id: svn://servers.simutrans.org@' --pretty=format:%B | tail -1 | sed -n 's%.*simutrans.org@\([0-9]*\).*%\1%p')"
        echo "FLAGS = -DREVISION=$revision " >>config.default
        echo "STATIC = 1" >>config.default
        cat config.default >>/dev/stderr
        echo "revision=$revision" >> $GITHUB_ENV

    - name: make
      run: make

    - name: distribute
      run: sh ./distribute.sh

    - name: Rename result
      run:  mv simu*.zip simulinux-x64-nightly.zip

    - name: Update binaries
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: Nightly
        name: Nightly built Ubuntu r${{ env.revision }}
        files: simulinux-x64-nightly.zip
        allow_override: true
        gzip: false
