name: Nightly build MacOS

on:
  push:
    tags:
      - 'Nightly_mac'

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: |
        brew install autoconf automake freetype libpng pkg-config sdl2

    - name: build
      run: |
        autoreconf -ivf
        ./configure CC=clang
        make BACKEND=sdl2 MULTI_THREAD=1 OPTIMISE=1 OSTYPE=mac USE_FREETYPE=1 USE_UPNP=0 USE_ZSTD=0 AV_FOUNDATION=1
        make OSX/getversion

    - name: distribute
      run: sh ./distribute.sh

    - name: Rename result
      run:  |
          ls *.zip >>/dev/stderr
          echo ::set-env name=LATEST::$(ls *.zip)
          mv sim*.zip simumac-nightly.zip

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./simumac-nightly.zip
        asset_name: simumac-nightly.zip
        tag: Nightly
        overwrite: true
