name: Nightly build Windows

on: [push]

jobs:
  makeobj_windows-nightly:
    name: makeobj
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: compile makeobj
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\makeobj\Makeobj.vcxproj /p:Configuration=Release
        cd $Env:GITHUB_WORKSPACE\

    - name: zip result
      run: Compress-Archive build\makeobj\Release\Makeobj.exe build\makeobj\Release\makeobj_windows-nightly.zip
      shell: pwsh

    - name: detect revision
      run: |
        $text = gc "$Env:GITHUB_WORKSPACE\revision.h"
        $revision=$text.Substring(17,5)
        echo "revision=$revision" >> $env:GITHUB_ENV
        echo $env:revision
      shell: pwsh

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/makeobj/Release/makeobj_windows-nightly.zip
        asset_name: makeobj_windows-nightly_r$env:revision.zip
        tag: rev_test
        overwrite: true
