name: Nightly build

on:
  push:
    tags:
      - 'Nightly_'

jobs:
  makeobj_windows-nightly:
    name: makeobj Windows
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: compile makeobj
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\makeobj\Makeobj.vcxproj /p:Configuration=Release
        cd $Env:GITHUB_WORKSPACE\

    - name: zip result
      run: Compress-Archive build\makeobj\Release\Makeobj.exe build\makeobj\Release\makeobj_windows-nightly.zip
      shell: pwsh

    - name: detect revision
      run: |
        $text = gc "$Env:GITHUB_WORKSPACE\revision.h"
        $revision=$text.Substring(17,5)
        echo "revision=$revision" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/makeobj/Release/makeobj_windows-nightly.zip
        asset_name: makeobj_windows-nightly_r${{ env.revision }}.zip
        tag: rev_test
        overwrite: true

  makeobj_linux-x64-nightly:
    name: makeobj Linux
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: install_dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -ym install autoconf
          sudo apt-get -ym install libpng-dev
          sudo apt-get -ym install libbz2-dev

      - name: setup
        run: |
          autoconf
          ./configure
          echo "STATIC = 1" >>config.default
          cat config.default >>/dev/stderr

      - name: make makeobj
        run: |
          cd makeobj
          make

      - name: zip result
        run: |
          cd makeobj
          zip -r -9 makeobj_linux-x64-nightly.zip makeobj

      - name: detect revision
        run: |
          read text < ./revision.h
          revision=${text:17:5}
          echo "revision=$revision" >> $GITHUB_ENV

      - name: Update binaries of Nightly Release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: makeobj/makeobj_linux-x64-nightly.zip
          asset_name: makeobj_linux-x64-nightly_r${{ env.revision }}.zip
          tag: rev_test
          overwrite: true

  makeobj-mac:
    name: makeobj macOS x86
    runs-on: macos-11.0

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure
        run: cp configs/config.${{ github.job }} config.default
      - name: Build
        run: make -j2 makeobj
      - name: zip result
        run: zip -r -9 makeobj_macos-nightly.zip build/default/makeobj/makeobj
      - name: detect revision
        run: |
          read text < ./revision.h
          revision=${text:17:5}
          echo "revision=$revision" >> $GITHUB_ENV
      - name: Upload Artifact (CI)
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: makeobj_macos-nightly.zip
          asset_name: makeobj_macos-x86-nightly_r${{ env.revision }}.zip
          #name: ${{ github.job }}-nightly
          #path: build/default/makeobj/makeobj
          tag: rev_test
          overwrite: true

