name: Simutrans Windows GDI

on:
  push:
    tags:
      - 'Nightly'

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: set revision
      run: |
        revision.cmd

    - name: compile simutrans
      run: |
        libs\buildTool\MSBuild\Current\Bin\MSBuild.exe Simutrans-GDI.vcxproj -property:Configuration=Debug
        copy Simutrans_GDI.exe simutrans\Simutrans.exe

    - name: zip result
      run: |
        libs\7zip\7z.exe a build\simuwin_GDI-nightly.zip simutrans\*

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/simuwin_GDI-nightly.zip
        asset_name: simuwin_GDI-nightly.zip
        tag: Nightly
        overwrite: true
