name: sim_linux64

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -ym install libsdl2-dev
        sudo apt-get -ym install libfreetype6-dev
        sudo apt-get -ym install libminiupnpc-dev
        sudo apt-get -ym install libzstd-dev
        sudo apt-get -ym install libbz2-dev
        sudo apt-get -ym install autoconf

    - name: setup
      run: |
        cd libs/bzip2-1.0.6
        make
        cd..
        rm libbz2.a
        cp bzip2-1.0.6/libbz2.a ./libbz2.a
        autoconf
        ./configure
        echo "CFLAGS += -DREVISION=$(svn info --show-item revision svn://servers.simutrans.org/simutrans) " >>config.default
        echo "CFLAGS += -std=c++11 " >>config.default
        echo "STATIC = 1" >>config.default
        cat config.default >>/dev/stderr

    - name: make
      run: |
        cd trunk
        make

    - name: distribute
      run: |
        cd trunk
        sh ./distribute.sh

    - name: Rename result
      run:  mv trunk/simu*.zip trunk/simulinux-x64-nightly.zip

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./simulinux-x64-nightly.zip
        asset_name: simulinux-x64-nightly.zip
        tag: Nightly
        overwrite: true

