name: Simutrans Windows SDL2

on:
  push:
    tags:
      - 'Nightly'

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: compile simutrans
      run: |
        libs\buildTool\MSBuild\Current\Bin\MSBuild.exe Simutrans-SDL2.vcxproj -property:Configuration=Debug
        copy Simutrans_SDL2.exe simutrans\Simutrans.exe
        copy libs\SDL2.dll simutrans\SDL2.dll

    - name: zip result
      run: |
        Compress-Archive -Path simutrans -DestinationPath build\simuwin_SDL2-nightly.zip

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/simuwin_SDL2-nightly.zip
        asset_name: simuwin_SDL2-nightly.zip
        tag: Nightly
        overwrite: true
