name: Simutrans Translate

on:
  push:
    tags:
      - 'translate'

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: check revision
      run: |
        svn log -l 1 > status.txt
        set /p string=<status.txt
        echo #define REVISION %string:~1,5% > revision.h

    - name: compile simutrans
      run: |
        libs\buildTool\MSBuild\Current\Bin\MSBuild.exe Simutrans-GDI.vcxproj -property:Configuration=Debug
        copy Simutrans_GDI.exe simutrans\Simutrans.exe

    - name: load translate files
      run: |
        libs\curl\curl.exe -L https://simutrans-germany.com/translator_page/base_text/download.php
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/data/language_pack-Base+texts.zip -OutFile language_pack.zip
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::ExtractToDirectory("language_pack.zip", "simutrans/text")

    - name: zip result
      run: |
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::CreateFromDirectory("simutrans", "simutrans_data.zip")

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: simutrans_data.zip
        asset__name: simutrans_data.zip
        tag: Nightly
        overwrite: true
