name: Nightly build Windows

on:
  push:
    tags:
      - 'Nightly'

jobs:
  makeobj_windows-nightly:
    name: makeobj
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: compile makeobj
      run: |
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\src\makeobj\Makeobj.vcxproj /p:Configuration=Release
        cd $Env:GITHUB_WORKSPACE\

    - name: zip result
      run: Compress-Archive src\build\makeobj\Release\Makeobj.exe src\build\makeobj\Release\makeobj_windows-nightly.zip
      shell: pwsh

    - name: detect revision
      run: |
        $text = gc "$Env:GITHUB_WORKSPACE\src\simutrans\revision.h"
        $revision=$text.Substring(17,5)
        echo "revision=$revision" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: src/build/makeobj/Release/makeobj_windows-nightly.zip
        asset_name: makeobj_windows-nightly_r${{ env.revision }}.zip
        tag: Nightly
        overwrite: true

  windows_GDI-nightly:
    name: Simutrans Windows GDI
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: compile simutrans
      run: |
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\Simutrans-GDI.vcxproj /p:Configuration=Release
        cd  $Env:GITHUB_WORKSPACE\
        copy build\GDI\simutrans_GDI.exe simutrans\Simutrans.exe

    - name: load translate files
      run: |
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/download.php
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/data/language_pack-Base+texts.zip -OutFile language_pack.zip

    - name: extract translate files
      run: Expand-Archive language_pack.zip simutrans/text
      shell: pwsh

    - name: delete ce translate files
      run: del simutrans/text/ce.tab
      shell: pwsh

    - name: zip result
      run:  Compress-Archive simutrans simuwin_GDI-nightly_x86.zip
      shell: pwsh

    - name: detect revision
      run: |
        cd  $Env:GITHUB_WORKSPACE\
        $text = gc "$Env:GITHUB_WORKSPACE\src\simutrans\revision.h"
        $revision=$text.Substring(17,5)
        echo "revision=$revision" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: simuwin_GDI-nightly_x86.zip
        asset_name: simuwin_GDI-nightly_x86_r${{ env.revision }}.zip
        tag: Nightly
        overwrite: true

  windows_SDL2-nightly:
    name: Simutrans Windows SDL2
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: compile simutrans
      run: |
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\Simutrans-SDL2.vcxproj /p:Configuration=git_actions
        cd $Env:GITHUB_WORKSPACE\
        copy Simutrans_SDL2.exe simutrans\Simutrans.exe
        copy libs\SDL2.dll simutrans\SDL2.dll

    - name: load translate files
      run: |
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/download.php
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/data/language_pack-Base+texts.zip -OutFile language_pack.zip

    - name: extract translate files
      run: Expand-Archive language_pack.zip src/simutrans/simutrans/text
      shell: pwsh

    - name: delete ce translate files
      run: del src/simutrans/simutrans/text/ce.tab
      shell: pwsh

    - name: zip result
      run:  Compress-Archive simutrans simuwin_SDL2-nightly_x86.zip
      shell: pwsh

    - name: detect revision
      run: |
        $text = gc "$Env:GITHUB_WORKSPACE\src\simutrans\revision.h"
        $revision=$text.Substring(17,5)
        echo "revision=$revision" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: simuwin_SDL2-nightly_x86.zip
        asset_name: simuwin_SDL2-nightly_x86_r${{ env.revision }}.zip
        tag: Nightly
        overwrite: true

  windows_server-nightly:
    name: Simutrans Windows Server
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: compile simutrans server
      run: |
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\Simutrans-Server.vcxproj /p:Configuration=git_actions
        cd $Env:GITHUB_WORKSPACE\
        copy Simutrans_Server.exe simutrans\Simutrans-Server.exe

    - name: load translate files
      run: |
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/download.php
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/data/language_pack-Base+texts.zip -OutFile language_pack.zip

    - name: extract translate files
      run: Expand-Archive language_pack.zip simutrans/text
      shell: pwsh

    - name: delete ce translate files
      run: del simutrans/text/ce.tab
      shell: pwsh

    - name: zip result
      run: Compress-Archive simutrans simuwin_server-nightly_x86.zip
      shell: pwsh

    - name: detect revision
      run: |
        $text = gc "$Env:GITHUB_WORKSPACE\src\simutrans\revision.h"
        $revision=$text.Substring(17,5)
        echo "revision=$revision" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: simuwin_server-nightly_x86.zip
        asset_name: simuwin_server-nightly_x86_r${{ env.revision }}.zip
        tag: Nightly
        overwrite: true

  windows_nettool:
    name: Simutrans Nettool
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: compile simutrans nettool
      run: |
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\src\nettool\Nettool.vcxproj /p:Configuration=release
        cd $Env:GITHUB_WORKSPACE\

    - name: zip result
      run: Compress-Archive src\nettool\Nettool.exe src\nettool\nettool_windows-nightly.zip
      shell: pwsh

    - name: detect revision
      run: |
        $text = gc "$Env:GITHUB_WORKSPACE\src\simutrans\revision.h"
        $revision=$text.Substring(17,5)
        echo "revision=$revision" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: src/nettool/nettool_windows-nightly.zip
        asset_name: nettool_windows-nightly_r${{ env.revision }}.zip
        tag: Nightly
        overwrite: true
