name: Makeobj Windows

on:
  push:
    tags:
      - 'Nightly'

jobs:
  makeobj_windoes-nightly:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: compile makeobj
      run: |
        cd makeobj
        ..\libs\buildTool\MSBuild\Current\Bin\MSBuild.exe Makeobj.vcxproj -property:Configuration=Release

    - name: zip result
      run: |
        libs\7zip\7z.exe a build\makeobj\Release\makeobj_windows-nightly.zip build\makeobj\Release\Makeobj.exe

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/makeobj/Release/makeobj_windows-nightly.zip
        asset_name: makeobj_windows-nightly.zip
        tag: Nightly
        overwrite: true

  windows_GDI-nightly:
    name: Simutrans Windows GDI

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: compile simutrans
      run: |
        libs\buildTool\MSBuild\Current\Bin\MSBuild.exe Simutrans-GDI.vcxproj -property:Configuration=Debug
        copy Simutrans_GDI.exe simutrans\Simutrans.exe

    - name: load translate files
      run: |
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/download.php
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/data/language_pack-Base+texts.zip -OutFile language_pack.zip
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::ExtractToDirectory("language_pack.zip", "simutrans/text")

    - name: zip result
      run: |
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::CreateFromDirectory("simutrans", "build\simuwin_GDI-nightly.zip")

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/simuwin_GDI-nightly.zip
        asset_name: simuwin_GDI-nightly.zip
        tag: Nightly
        overwrite: true

  windows_SDL2-nightly:
    name: Simutrans Windows SDL2

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: compile simutrans
      run: |
        libs\buildTool\MSBuild\Current\Bin\MSBuild.exe Simutrans-SDL2.vcxproj -property:Configuration=Debug
        copy Simutrans_SDL2.exe simutrans\Simutrans.exe
        copy libs\SDL2.dll simutrans\SDL2.dll

    - name: load translate files
      run: |
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/download.php
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/data/language_pack-Base+texts.zip -OutFile language_pack.zip
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::ExtractToDirectory("language_pack.zip", "simutrans/text")

    - name: zip result
      run: |
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::CreateFromDirectory("simutrans", "build\simuwin_SDL2-nightly.zip")

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/simuwin_SDL2-nightly.zip
        asset_name: simuwin_SDL2-nightly.zip
        tag: Nightly
        overwrite: true
