name: Makeobj Windows

on:
  push:
    tags:
      - 'Nightly'

jobs:
  makeobj_windows-nightly:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: compile makeobj
      run: libs\buildTool\MSBuild\Current\Bin\MSBuild.exe makeobj\Makeobj.vcxproj -property:Configuration=Release

    - name: zip result
      run: Compress-Archive build\makeobj\Release\Makeobj.exe build\makeobj\Release\makeobj_windows-nightly.zip
      shell: pwsh

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/makeobj/Release/makeobj_windows-nightly.zip
        asset_name: makeobj_windows-nightly.zip
        tag: Nightly
        overwrite: true

  windows_GDI-nightly:
    name: Simutrans Windows GDI

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: compile simutrans
      run: |
        libs\buildTool\MSBuild\Current\Bin\MSBuild.exe Simutrans-GDI.vcxproj -property:Configuration=Debug
        copy Simutrans_GDI.exe simutrans\Simutrans.exe

    - name: load translate files
      run: |
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/download.php
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/data/language_pack-Base+texts.zip -OutFile language_pack.zip

    - name: extract translate files
      run: Expand-Archive language_pack.zip simutrans/text
      shell: pwsh

    - name: zip result
      run: Compress-Archive simutrans build\simuwin_GDI-nightly.zip
      shell: pwsh

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/simuwin_GDI-nightly.zip
        asset_name: simuwin_GDI-nightly.zip
        tag: Nightly
        overwrite: true

  windows_SDL2-nightly:
    name: Simutrans Windows SDL2

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: compile simutrans
      run: |
        libs\buildTool\MSBuild\Current\Bin\MSBuild.exe Simutrans-SDL2.vcxproj -property:Configuration=Debug
        copy Simutrans_SDL2.exe simutrans\Simutrans.exe
        copy libs\SDL2.dll simutrans\SDL2.dll

    - name: load translate files
      run: |
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/download.php
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/data/language_pack-Base+texts.zip -OutFile language_pack.zip

    - name: extract translate files
      run: Expand-Archive language_pack.zip simutrans/text
      shell: pwsh

    - name: zip result
      run: Compress-Archive simutrans build\simuwin_SDL2-nightly.zip
      shell: pwsh

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/simuwin_SDL2-nightly.zip
        asset_name: simuwin_SDL2-nightly.zip
        tag: Nightly
        overwrite: true

  windows_server-nightly:
    name: Simutrans Windows Server

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: compile simutrans server
      run: |
        libs\buildTool\MSBuild\Current\Bin\MSBuild.exe Simutrans-Server.vcxproj -property:Configuration=Debug
        copy Simutrans_Server.exe simutrans\Simutrans-Server.exe

    - name: load translate files
      run: |
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/download.php
        Invoke-WebRequest -Uri https://simutrans-germany.com/translator_page/base_text/data/language_pack-Base+texts.zip -OutFile language_pack.zip

    - name: extract translate files
      run: Expand-Archive language_pack.zip simutrans/text
      shell: pwsh

    - name: zip result
      run: Compress-Archive simutrans build\simuwin_server-nightly.zip
      shell: pwsh

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/simuwin_server-nightly.zip
        asset_name: simuwin_server-nightly.zip
        tag: Nightly
        overwrite: true

  windows_nettool:
    name: Simutrans Nettool

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: compile simutrans nettool
      run: libs\buildTool\MSBuild\Current\Bin\MSBuild.exe nettools\Nettool.vcxproj -property:Configuration=Debug

    - name: zip result
      run: Compress-Archive nettools\Nettool.exe nettools\nettool_windows-nightly.zip
      shell: pwsh

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: nettools\nettool_windows-nightly.zip
        asset_name: nettool_windows-nightly.zip
        tag: Nightly
        overwrite: true
